import type { RspressPlugin } from '@rspress/core';
import path from 'path';
import fs from 'fs';
import { parser } from 'stream-json';
import { chain } from 'stream-chain';
import { streamArray } from 'stream-json/streamers/stream-array.js';
import batch from 'stream-chain/utils/batch.js';
import type { ConfigurationOptions } from 'typesense/lib/Typesense/Configuration';
import type { CustomSettings } from './types';
import { TypesenseHelper } from './typesenseHelper';
import { RspressConverter } from './transformDocument';

export interface TypesensePluginOptions {
  typesenseOptions: ConfigurationOptions;
  collectionName: string;
  customSettings?: CustomSettings;
}

export function pluginTypesense(
  options: TypesensePluginOptions,
): RspressPlugin {
  return {
    name: 'rspress-plugin-typesense',
    config(config) {
      return config;
    },

    async afterBuild(config, isProd) {
      if (!isProd) return;

      // @ts-ignore
      const isVersioned = config.search?.versioned ?? true;
      const defaultLang = config.lang || 'en';

      // Rspress outputs search indices to /static
      const staticDir = path.join(config.outDir || 'doc_build', 'static');

      if (!fs.existsSync(staticDir)) {
        console.warn(
          `[TypesensePlugin] Static directory not found at ${staticDir}. Skipping indexing.`,
        );
        return;
      }

      // Find all JSON index files generated by Rspress
      const files = fs
        .readdirSync(staticDir)
        .filter((f) => f.startsWith('search_index') && f.endsWith('.json'));

      for (const file of files) {
        // Parse filename: search_index.[version?].[locale].[hash].json
        // Examples: search_index.v1.en.532cba58.json OR search_index.en.532cba58.json
        const filename = file
          .replace(/^search_index\.?/, '')
          .replace(/\.json$/, '');
        const parts = filename ? filename.split('.') : [];

        // Remove last part as it is the Rspress build hash
        if (parts.length > 0) parts.pop();

        let version = '';
        let locale = defaultLang;

        if (isVersioned && parts.length > 0) {
          version = parts.shift() || ''; // Extract version e.g. 'v1'
        }

        if (parts.length > 0) {
          locale = parts.shift() || defaultLang; // Extract locale e.g. 'en', 'zh'
        }

        // Create desired collection name format based on constraints
        let aliasName = options.collectionName;
        if (isVersioned && version) {
          aliasName += `_${version}`;
        }
        aliasName += `_${locale}`;

        const collectionNameTmp = `${aliasName}_${Date.now()}`;

        console.log(`\n[TypesensePlugin] Processing index file: ${file}`);
        console.log(`[TypesensePlugin] Target Collection Alias: ${aliasName}`);

        const helper = new TypesenseHelper(
          options.typesenseOptions,
          aliasName,
          collectionNameTmp,
          options.customSettings || null,
          locale,
        );

        await helper.init();
        await helper.createTmpCollection();

        const indexPath = path.join(staticDir, file);

        const pipeline = chain([
          fs.createReadStream(indexPath),
          parser(),
          streamArray(),
          batch(100),
        ]);

        try {
          for await (const chunk of pipeline) {
            const records = chunk.flatMap((item: any) => {
              return RspressConverter.getRecords(item.value);
            });
            if (records.length > 0) {
              await helper.addRecords(records, file, false);
            }
          }

          await helper.commitTmpCollection();
          console.log(`[TypesensePlugin] Indexing complete for ${aliasName}!`);
        } catch (error) {
          console.error(`[TypesensePlugin] Failed to index ${file}:`, error);
          throw error;
        }
      }
    },
  };
}
